In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("C://Users//akash//ML-PROJECTS//Carpriceprediction//data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [3]:
df['Popularity'].unique()

array([3916, 3105,  819,  617, 1013, 2009,  870,  586,  436, 2774,  113,
       2031,  416,   67,  210, 1715,  376,  549, 1439,  535, 2202,   26,
        481, 5657, 1624, 1720,  520, 1385, 1851, 1158,   61,  640,  873,
          2,  155,  204,   86,  238,  454,  259,  258,  613,  190,  105,
         21,  130, 1391,  820], dtype=int64)

In [4]:
df['Transmission Type'].unique()

array(['MANUAL', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'DIRECT_DRIVE',
       'UNKNOWN'], dtype=object)

In [5]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [6]:
df['Driven_Wheels'].unique()

array(['rear wheel drive', 'front wheel drive', 'all wheel drive',
       'four wheel drive'], dtype=object)

In [7]:
df['Year'].unique()

array([2011, 2012, 2013, 1992, 1993, 1994, 2017, 1991, 2016, 1990, 2015,
       1996, 1997, 1998, 2014, 1999, 2002, 2003, 2004, 1995, 2007, 2008,
       2009, 2001, 2010, 2000, 2005, 2006], dtype=int64)

In [8]:
df.shape

(11914, 16)

In [9]:
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [11]:
df1 = df.drop(columns=['Engine Fuel Type','Transmission Type','Market Category','Model','Vehicle Size','Vehicle Style','Driven_Wheels'],axis='columns')
df1.head()

Make  Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
0  BMW  2011      335.0               6.0              2.0           26   
1  BMW  2011      300.0               6.0              2.0           28   
2  BMW  2011      300.0               6.0              2.0           28   
3  BMW  2011      230.0               6.0              2.0           28   
4  BMW  2011      230.0               6.0              2.0           28   

   city mpg  Popularity   MSRP  
0        19        3916  46135  
1        19        3916  40650  
2        20        3916  36350  
3        18        3916  29450  
4        18        3916  34500

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [13]:
df1.isnull().sum()

Make                 0
Year                 0
Engine HP           69
Engine Cylinders    30
Number of Doors      6
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [14]:
#df1['Engine HP'].fillna(df1['Engine HP'].mean(), inplace=True)

In [15]:
#df1['Engine Cylinders'].fillna(df1['Engine Cylinders'].median(), inplace=True)
#df1['Number of Doors'].fillna(df1['Number of Doors'].mean(), inplace=True)

In [16]:
df2=df1.dropna()
df2.isnull().sum()

Make                0
Year                0
Engine HP           0
Engine Cylinders    0
Number of Doors     0
highway MPG         0
city mpg            0
Popularity          0
MSRP                0
dtype: int64

In [17]:
#df1.isnull().sum()

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()
df2['Make'] = le.fit_transform(df2['Make'])
#df2['Model'] = le.fit_transform(df2['Model'])
#df2['Driven_Wheels'] = le.fit_transform(df2['Driven_Wheels'])
#df2['Vehicle Size'] = le.fit_transform(df2['Vehicle Size'])
#df2['Vehicle Style'] = le.fit_transform(df2['Vehicle Style'])

<ipython-input-19-c7b9b5f8c468>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Make'] = le.fit_transform(df2['Make'])


In [20]:
df2.head()

Make  Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
0     4  2011      335.0               6.0              2.0           26   
1     4  2011      300.0               6.0              2.0           28   
2     4  2011      300.0               6.0              2.0           28   
3     4  2011      230.0               6.0              2.0           28   
4     4  2011      230.0               6.0              2.0           28   

   city mpg  Popularity   MSRP  
0        19        3916  46135  
1        19        3916  40650  
2        20        3916  36350  
3        18        3916  29450  
4        18        3916  34500

In [21]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [22]:
X=df2.drop('MSRP', axis='columns')
y=df2['MSRP']

In [23]:
scaled_df = scaler.fit_transform(X)
#scaled_y = scaler.fit_transform(y)

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(scaled_df,y,test_size=0.2,random_state=2)

In [25]:
model=LinearRegression()
model.fit(X_train,y_train)
model.predict(X_test)
#model.score(X,y)

array([21377.90757649, 34564.94854917, 65819.87496431, ...,
       60328.84956717, 17875.6285539 , 22566.59816512])

In [26]:
model.score(X_test,y_test)

0.37962722590286

In [27]:
model.score(X_train,y_train)

0.5096597892667055

In [28]:
from sklearn.metrics import r2_score
X_train_prediction=model.predict(X_train)
train_data_acc = r2_score(y_train,X_train_prediction)

X_test_prediction=model.predict(X_test)
test_data_acc = r2_score(y_test,X_test_prediction)

In [29]:
print("accuracy at train is ",train_data_acc)
print("accuracy at test is ",test_data_acc)


accuracy at train is  0.5096597892667055
accuracy at test is  0.37962722590286
